### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by userStarlight** [IsraelHikingMap/graphhopper-docker-image-push#35]
graphhopper:
    restart:always
    container_name: graphhopper
    image: israelhikingmap/graphhopper:6.0
    command: -i /maps/taiwan-latest.osm.pbf --host 0.0.0.0
    volumes:
      - ./data/SiteMapRouting/maps:/maps
    ports:
      - 8989:8989
我使用此方式部署docker由于osm.pbf文件过大,导致报错:内存溢出,我该怎么修改这段配置

**Comment by HarelM** [comment]
Google translate:
>我使用此方式部署docker由于osm.pbf文件过大,导致报错:内存溢出,我该怎么修改这段配置
I use this method to deploy docker because the osm.pbf file is too large, resulting in an error: memory overflow. How should I modify this configuration?

As written in the readme here, you can set `JAVA_OPTS: "-Xmx1g -Xms1g"` environment variable to a bigger number to supporting import of bigger files.

Use
```
environment:
    - JAVA_OPTS: "-Xmx5g -Xms5g"
```
